package com.string.manipulation;
/*
389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

TC : o(n)
SC: o(1)
 */
public class FindTheDifference {

    public static void main(String[] args) {
        System.out.println(new FindTheDifference().findTheDifference("abcd","abcde"));
    }
    public char findTheDifference(String s, String t) {
        char res = 0;

        for(int i=0;i<s.length();i++){
            res ^= s.charAt(i);
        }

        for(int i=0;i<t.length();i++){
            res ^= t.charAt(i);
        }
        return res;
    }
}
